### ISSUE TITLE
[MOVIE]: Interstellar (2014)

### ISSUE THREAD

**Issue by alexdelfol** [LizardByte/ThemerrDB#4940]
### Database URL

https://www.themoviedb.org/movie/157336

### YouTube Theme Song Video URL

https://youtu.be/JuSsvM8B4Jc?si=pj_2PN7k_-ewHCtt

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
There is a theme in the database for this movie already and a replacement reason is not listed. We would normally close these out without updating the theme since there is no replacement reason listed. However, I believe this song is more popular than the existing theme in our database. @LizardByte-bot approve

**Comment by OcifferAction** [comment]
@LizardByte-bot approve
