### ISSUE TITLE
[MOVIE]: A Quiet Place (2018)

### ISSUE THREAD

**Issue by Markus231086** [LizardByte/ThemerrDB#5203]
### Database URL

https://www.themoviedb.org/movie/447332

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=ttiU0cKhGlw

### Additional Information

- [ ] This is a replacement request. If checked, please provide a reason below.

**Comment by OcifferAction** [comment]
Movie already has theme in database and no replacement reason was listed. Closing as duplicate.

**Comment by Markus231086** [comment]
Hey, Why does Plex show me that there is no theme? 🤔--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 09.07.24, 15:11 schrieb OcifferAction ***@***.***>:

   
  Movie already has theme in database and no replacement reason was listed. Closing as duplicate.

**Comment by OcifferAction** [comment]
It's possible that Plex failed to download the theme or that the video is not available in your country which caused the issue. You can verify by going to your server's Themerr web UI. 

Typically it can be accessed @ http://your_plex_server_IP:9494. You can verify the address and port from your Themerr configuration within your Plex plugins folder or within the Plex UI by going to Settings > Plugins > Hover over the Themerr plugin to show the settings gear button > then down to Web UI Port.

Also, you can always check the ThemerrDB website @ [https://app.lizardbyte.dev/ThemerrDB/](https://app.lizardbyte.dev/ThemerrDB/) to verify that the theme exists in the database. From there you can attempt to watch the YouTube video in the database to see if it has a country restriction on it.

You can submit a new video that works for you, as long as it conforms to the guidelines and is playable within the US. Make sure to put a reason for replacement anytime you're replacing a theme that already exists. Otherwise it will be closed as a duplicate.
